/* --- NEET-OS CENTRAL DATABASE --- */
const NEET_DATABASE = {
    chapters: [
        // I have integrated all 99 chapters you provided here
        { id: 1,  name: "The Living World", subject: "Biology", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 2,  name: "Biological Classification", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 3,  name: "Plant Kingdom", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 4,  name: "Animal Kingdom", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 5,  name: "Morphology of Flowering Plants", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 6,  name: "Anatomy of Flowering Plants", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 7,  name: "Structural Organisation in Animals", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 8,  name: "Cell: The Unit of Life", subject: "Biology", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 9,  name: "Biomolecules", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 10, name: "Cell Cycle and Cell Division", subject: "Biology", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 11, name: "Transport in Plants", subject: "Biology", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 12, name: "Mineral Nutrition", subject: "Biology", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 13, name: "Photosynthesis in Higher Plants", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 14, name: "Respiration in Plants", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 15, name: "Plant Growth and Development", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 16, name: "Digestion and Absorption", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 17, name: "Breathing and Exchange of Gases", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 18, name: "Body Fluids and Circulation", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 19, name: "Excretory Products and Elimination", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 20, name: "Locomotion and Movement", subject: "Biology", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 21, name: "Neural Control and Coordination", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 22, name: "Chemical Coordination and Integration", subject: "Biology", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 23, name: "Some Basic Concepts of Chemistry", subject: "Chemistry", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 24, name: "Structure of Atom", subject: "Chemistry", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 25, name: "Classification of Elements and Periodicity", subject: "Chemistry", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 26, name: "Chemical Bonding and Molecular Structure", subject: "Chemistry", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 27, name: "States of Matter", subject: "Chemistry", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 28, name: "Thermodynamics (Chemistry)", subject: "Chemistry", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 29, name: "Equilibrium", subject: "Chemistry", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 30, name: "Redox Reactions", subject: "Chemistry", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 31, name: "Hydrogen", subject: "Chemistry", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 32, name: "s-Block Elements", subject: "Chemistry", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 33, name: "p-Block Elements (11th)", subject: "Chemistry", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 34, name: "Organic Chemistry – Basic Principles", subject: "Chemistry", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 35, name: "Hydrocarbons", subject: "Chemistry", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 36, name: "Environmental Chemistry", subject: "Chemistry", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 37, name: "Physical World", subject: "Physics", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 38, name: "Units and Measurements", subject: "Physics", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 39, name: "Motion in a Straight Line", subject: "Physics", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 40, name: "Motion in a Plane", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 41, name: "Laws of Motion", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 42, name: "Work, Energy and Power", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 43, name: "System of Particles and Rotational Motion", subject: "Physics", class: "11", weightage: "Critical", progress: 0, streak: 0 },
        { id: 44, name: "Gravitation", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 45, name: "Mechanical Properties of Solids", subject: "Physics", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 46, name: "Mechanical Properties of Fluids", subject: "Physics", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 47, name: "Thermal Properties of Matter", subject: "Physics", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 48, name: "Thermodynamics (Physics)", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 49, name: "Kinetic Theory", subject: "Physics", class: "11", weightage: "Low", progress: 0, streak: 0 },
        { id: 50, name: "Oscillations", subject: "Physics", class: "11", weightage: "Medium", progress: 0, streak: 0 },
        { id: 51, name: "Waves", subject: "Physics", class: "11", weightage: "High", progress: 0, streak: 0 },
        { id: 52, name: "Reproduction in Organisms", subject: "Biology", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 53, name: "Sexual Reproduction in Flowering Plants", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 54, name: "Human Reproduction", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 55, name: "Reproductive Health", subject: "Biology", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 56, name: "Principles of Inheritance and Variation", subject: "Biology", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 57, name: "Molecular Basis of Inheritance", subject: "Biology", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 58, name: "Evolution", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 59, name: "Human Health and Disease", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 60, name: "Strategies for Enhancement in Food Production", subject: "Biology", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 61, name: "Microbes in Human Welfare", subject: "Biology", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 62, name: "Biotechnology: Principles and Processes", subject: "Biology", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 63, name: "Biotechnology and its Applications", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 64, name: "Organisms and Populations", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 65, name: "Ecosystem", subject: "Biology", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 66, name: "Biodiversity and Conservation", subject: "Biology", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 67, name: "Environmental Issues", subject: "Biology", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 68, name: "Solid State", subject: "Chemistry", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 69, name: "Solutions", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 70, name: "Electrochemistry", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 71, name: "Chemical Kinetics", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 72, name: "Surface Chemistry", subject: "Chemistry", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 73, name: "General Principles of Metallurgy", subject: "Chemistry", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 74, name: "p-Block Elements (12th)", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 75, name: "d and f Block Elements", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 76, name: "Coordination Compounds", subject: "Chemistry", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 77, name: "Haloalkanes and Haloarenes", subject: "Chemistry", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 78, name: "Alcohols, Phenols and Ethers", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 79, name: "Aldehydes, Ketones and Carboxylic Acids", subject: "Chemistry", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 80, name: "Amines", subject: "Chemistry", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 81, name: "Biomolecules (Chemistry)", subject: "Chemistry", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 82, name: "Polymers", subject: "Chemistry", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 83, name: "Chemistry in Everyday Life", subject: "Chemistry", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 84, name: "Electric Charges and Fields", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 85, name: "Electrostatic Potential and Capacitance", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 86, name: "Current Electricity", subject: "Physics", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 87, name: "Moving Charges and Magnetism", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 88, name: "Magnetism and Matter", subject: "Physics", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 89, name: "Electromagnetic Induction", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 90, name: "Alternating Current", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 91, name: "Electromagnetic Waves", subject: "Physics", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 92, name: "Ray Optics", subject: "Physics", class: "12", weightage: "Critical", progress: 0, streak: 0 },
        { id: 93, name: "Wave Optics", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 94, name: "Dual Nature of Radiation and Matter", subject: "Physics", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 95, name: "Atoms", subject: "Physics", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 96, name: "Nuclei", subject: "Physics", class: "12", weightage: "Medium", progress: 0, streak: 0 },
        { id: 97, name: "Semiconductor Electronics", subject: "Physics", class: "12", weightage: "High", progress: 0, streak: 0 },
        { id: 98, name: "Communication Systems", subject: "Physics", class: "12", weightage: "Low", progress: 0, streak: 0 },
        { id: 99, name: "Experimental Skills", subject: "Physics", class: "12", weightage: "Medium", progress: 0, streak: 0 }
    ],
    user: {
        dailyTargets: ["Finish 20 Bio MCQs", "Solve 5 Physics Numericals", "Revise Chemistry Bonds"],
        todayHours: 0
    }
};

const Storage = {
    save: (data) => localStorage.setItem('NEET_OS_DATA', JSON.stringify(data)),
    load: () => JSON.parse(localStorage.getItem('NEET_OS_DATA')) || NEET_DATABASE
};

let CurrentState = Storage.load();